-- One‑time setup: copies queries and installs parser
vim.api.nvim_create_autocmd("FileType", {
  pattern = "liotree",
  callback = function()
    vim.treesitter.start()
  end,
})
vim.api.nvim_create_autocmd("BufNewFile", {
  pattern = "*.liotree",
  command = "set filetype=liotree",
})
vim.api.nvim_create_autocmd("BufRead", {
  pattern = "*.liotree",
  command = "set filetype=liotree",
})

-- Lovdog Tree Format
vim.filetype.add({
  extension = {
    liotree = "liotree",
  },
})

local parser_config = require("nvim-treesitter.parsers").get_parser_configs()

parser_config.liotree = {
  install_info = {
    url = "~/.config/nvim/TreeSitter-Lab/ts-liotree", -- Use the absolute path to your project folder
    files = {"src/parser.c"},             -- This was generated by 'tree-sitter generate'
    branch = "main",
  },
  filetype = "liotree", -- This must match the filetype used in Neorg
}

-- Define your palette based on your Vimscript values
local hl = vim.api.nvim_set_hl
local liotree_groups = {
    ["@comment.liotree"]   = { fg = "#66ddee", force=true, italic = true },
    ["@liotree.directory"] = { fg = "#ffdd88", force=true, bold   = true },
    ["@liotree.file"]      = { fg = "#ffffbb", force=true},
    ["@liotree.bar"]       = { link = "Keyword" },
}
vim.api.nvim_create_autocmd("ColorScheme", {
  pattern = "*",
  callback = function()
    for group, settings in pairs(liotree_groups) do
        hl(0, group, settings)
    end
  end,
})

-- Define the folding logic in Lua
local function liotree_fold_level(lnum)
  -- 1. Ask Tree-sitter first (This handles the multi-line comments)
  local ts_level = vim.treesitter.foldexpr(lnum)
  if ts_level ~= "0" and ts_level ~= 0 then
    return ts_level
  end

  local line = vim.fn.getline(lnum)

  -- 2. Tree-bar logic for the structure
  local markers = line:match("^%s*|[%-+]+")
  if markers then
    local symbols = markers:match("[%-%+]+")
    return tostring(#symbols)
  end

  -- 3. Root level
  if line:match("^%s*|[^%-+%s]") then
    return "1"
  end

  -- 4. Continuity (Lines starting with | followed by spaces)
  if line:match("^%s*|%s%s+") then
    return "="
  end

  return "0"
end

_G.LioTreeFoldLevel = liotree_fold_level

vim.api.nvim_create_autocmd("FileType", {
  pattern = "liotree",
  callback = function()
    vim.opt_local.foldmethod = "expr"
    vim.opt_local.foldexpr = "v:lua.LioTreeFoldLevel(v:lnum)"
    
    -- Safety settings
    vim.opt_local.foldlevel = 99
    vim.cmd('normal! zx')
  end,
})
