/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  aux_sym_blank_line_token1 = 2,
  aux_sym_structure_line_token1 = 3,
  aux_sym_comment_line_token1 = 4,
  sym_lateral_bar = 5,
  sym_depth_marks = 6,
  aux_sym_inline_comment_token1 = 7,
  sym_comment_start = 8,
  sym_comment_end = 9,
  sym_comment_text = 10,
  sym_quoted_dirname = 11,
  sym_quoted_filename = 12,
  sym_unquoted_dirname = 13,
  sym_unquoted_filename = 14,
  sym_unclosed_quoted_string = 15,
  sym_source_file = 16,
  sym__line = 17,
  sym_blank_line = 18,
  sym_root_line = 19,
  sym_structure_line = 20,
  sym_comment_line = 21,
  sym_name = 22,
  sym_inline_comment = 23,
  aux_sym_source_file_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [aux_sym_blank_line_token1] = "blank_line_token1",
  [aux_sym_structure_line_token1] = "structure_line_token1",
  [aux_sym_comment_line_token1] = "comment_line_token1",
  [sym_lateral_bar] = "lateral_bar",
  [sym_depth_marks] = "depth_marks",
  [aux_sym_inline_comment_token1] = "inline_comment_token1",
  [sym_comment_start] = "comment_start",
  [sym_comment_end] = "comment_end",
  [sym_comment_text] = "comment_text",
  [sym_quoted_dirname] = "quoted_dirname",
  [sym_quoted_filename] = "quoted_filename",
  [sym_unquoted_dirname] = "unquoted_dirname",
  [sym_unquoted_filename] = "unquoted_filename",
  [sym_unclosed_quoted_string] = "unclosed_quoted_string",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_blank_line] = "blank_line",
  [sym_root_line] = "root_line",
  [sym_structure_line] = "structure_line",
  [sym_comment_line] = "comment_line",
  [sym_name] = "name",
  [sym_inline_comment] = "inline_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_blank_line_token1] = aux_sym_blank_line_token1,
  [aux_sym_structure_line_token1] = aux_sym_structure_line_token1,
  [aux_sym_comment_line_token1] = aux_sym_comment_line_token1,
  [sym_lateral_bar] = sym_lateral_bar,
  [sym_depth_marks] = sym_depth_marks,
  [aux_sym_inline_comment_token1] = aux_sym_inline_comment_token1,
  [sym_comment_start] = sym_comment_start,
  [sym_comment_end] = sym_comment_end,
  [sym_comment_text] = sym_comment_text,
  [sym_quoted_dirname] = sym_quoted_dirname,
  [sym_quoted_filename] = sym_quoted_filename,
  [sym_unquoted_dirname] = sym_unquoted_dirname,
  [sym_unquoted_filename] = sym_unquoted_filename,
  [sym_unclosed_quoted_string] = sym_unclosed_quoted_string,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_blank_line] = sym_blank_line,
  [sym_root_line] = sym_root_line,
  [sym_structure_line] = sym_structure_line,
  [sym_comment_line] = sym_comment_line,
  [sym_name] = sym_name,
  [sym_inline_comment] = sym_inline_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_blank_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_structure_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_lateral_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_depth_marks] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_inline_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment_start] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_end] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_text] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_dirname] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_dirname] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_unclosed_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_root_line] = {
    .visible = true,
    .named = true,
  },
  [sym_structure_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_depth = 1,
  field_name = 2,
  field_text = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_depth] = "depth",
  [field_name] = "name",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 2},
  [1] =
    {field_text, 3},
  [2] =
    {field_depth, 2},
    {field_name, 4},
  [4] =
    {field_text, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 8,
  [14] = 9,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 11,
  [23] = 23,
  [24] = 10,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_blank_line_token1);
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\'') ADVANCE(42);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '|') ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == '|') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '\n', 10,
        '"', 40,
        '\'', 42,
        '>', 20,
        '|', 16,
        '\t', 6,
        ' ', 6,
        '+', 17,
        '-', 17,
      );
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(48);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '|') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LF);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_blank_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_blank_line_token1);
      if (eof) ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_structure_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_line_token1);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_lateral_bar);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_depth_marks);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_inline_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_inline_comment_token1);
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment_start);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '|') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_quoted_dirname);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_quoted_dirname);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(1);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_quoted_dirname);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_quoted_dirname);
      if (lookahead == '\'') ADVANCE(33);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(3);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_quoted_dirname);
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_quoted_dirname);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(48);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_quoted_filename);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(1);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_quoted_filename);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_quoted_filename);
      if (lookahead == '\'') ADVANCE(33);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(3);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_quoted_filename);
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_quoted_filename);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(48);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_quoted_filename);
      if (lookahead == '/') ADVANCE(23);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_unquoted_dirname);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(41);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(49);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_unquoted_dirname);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '\'') ADVANCE(33);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(51);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_unquoted_dirname);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(1);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_unquoted_dirname);
      if (lookahead == '\'') ADVANCE(33);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(3);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_unquoted_dirname);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(48);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_unquoted_filename);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(41);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(49);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_unquoted_filename);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(41);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(49);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_unquoted_filename);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '\'') ADVANCE(33);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(51);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_unquoted_filename);
      if (lookahead == '\n') ADVANCE(46);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(43);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(51);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_unquoted_filename);
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(1);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_unquoted_filename);
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(1);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_unquoted_filename);
      if (lookahead == '\'') ADVANCE(33);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(3);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_unquoted_filename);
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(47);
      if (lookahead == '>' ||
          lookahead == '|') ADVANCE(3);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_unquoted_filename);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_unclosed_quoted_string);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(50);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_unclosed_quoted_string);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(50);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_unclosed_quoted_string);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(52);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_unclosed_quoted_string);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(52);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 13},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 19},
  [9] = {.lex_state = 19},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 19},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 19},
  [14] = {.lex_state = 19},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 19},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 22},
  [31] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_blank_line_token1] = ACTIONS(1),
    [aux_sym_structure_line_token1] = ACTIONS(1),
    [aux_sym_comment_line_token1] = ACTIONS(1),
    [sym_depth_marks] = ACTIONS(1),
    [sym_comment_start] = ACTIONS(1),
    [sym_quoted_dirname] = ACTIONS(1),
    [sym_quoted_filename] = ACTIONS(1),
    [sym_unquoted_dirname] = ACTIONS(1),
    [sym_unquoted_filename] = ACTIONS(1),
    [sym_unclosed_quoted_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym__line] = STATE(17),
    [sym_blank_line] = STATE(17),
    [sym_root_line] = STATE(17),
    [sym_structure_line] = STATE(17),
    [sym_comment_line] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_blank_line_token1] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(28), 5,
      sym__line,
      sym_blank_line,
      sym_root_line,
      sym_structure_line,
      sym_comment_line,
  [17] = 4,
    ACTIONS(12), 1,
      aux_sym_comment_line_token1,
    ACTIONS(14), 1,
      sym_depth_marks,
    STATE(8), 1,
      sym_name,
    ACTIONS(16), 5,
      sym_quoted_dirname,
      sym_quoted_filename,
      sym_unquoted_dirname,
      sym_unquoted_filename,
      sym_unclosed_quoted_string,
  [34] = 4,
    ACTIONS(5), 1,
      aux_sym_blank_line_token1,
    ACTIONS(18), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(18), 5,
      sym__line,
      sym_blank_line,
      sym_root_line,
      sym_structure_line,
      sym_comment_line,
  [51] = 4,
    ACTIONS(12), 1,
      aux_sym_comment_line_token1,
    ACTIONS(20), 1,
      sym_depth_marks,
    STATE(13), 1,
      sym_name,
    ACTIONS(22), 5,
      sym_quoted_dirname,
      sym_quoted_filename,
      sym_unquoted_dirname,
      sym_unquoted_filename,
      sym_unclosed_quoted_string,
  [68] = 2,
    STATE(9), 1,
      sym_name,
    ACTIONS(16), 5,
      sym_quoted_dirname,
      sym_quoted_filename,
      sym_unquoted_dirname,
      sym_unquoted_filename,
      sym_unclosed_quoted_string,
  [79] = 2,
    STATE(14), 1,
      sym_name,
    ACTIONS(22), 5,
      sym_quoted_dirname,
      sym_quoted_filename,
      sym_unquoted_dirname,
      sym_unquoted_filename,
      sym_unclosed_quoted_string,
  [90] = 4,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 1,
      anon_sym_LF,
    ACTIONS(28), 1,
      aux_sym_inline_comment_token1,
    STATE(21), 1,
      sym_inline_comment,
  [103] = 4,
    ACTIONS(28), 1,
      aux_sym_inline_comment_token1,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    ACTIONS(32), 1,
      anon_sym_LF,
    STATE(19), 1,
      sym_inline_comment,
  [116] = 2,
    ACTIONS(36), 1,
      sym_lateral_bar,
    ACTIONS(34), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [124] = 2,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 2,
      anon_sym_LF,
      aux_sym_inline_comment_token1,
  [132] = 2,
    ACTIONS(44), 1,
      sym_comment_end,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [140] = 3,
    ACTIONS(26), 1,
      anon_sym_LF,
    ACTIONS(28), 1,
      aux_sym_inline_comment_token1,
    STATE(21), 1,
      sym_inline_comment,
  [150] = 3,
    ACTIONS(28), 1,
      aux_sym_inline_comment_token1,
    ACTIONS(32), 1,
      anon_sym_LF,
    STATE(19), 1,
      sym_inline_comment,
  [160] = 2,
    ACTIONS(48), 1,
      sym_comment_end,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [168] = 1,
    ACTIONS(7), 2,
      ts_builtin_sym_end,
      aux_sym_blank_line_token1,
  [173] = 2,
    ACTIONS(18), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      anon_sym_LF,
  [180] = 2,
    ACTIONS(50), 1,
      anon_sym_LF,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
  [187] = 1,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [192] = 1,
    ACTIONS(56), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [197] = 1,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [202] = 1,
    ACTIONS(40), 2,
      anon_sym_LF,
      aux_sym_inline_comment_token1,
  [207] = 1,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      anon_sym_LF,
  [212] = 2,
    ACTIONS(34), 1,
      anon_sym_LF,
    ACTIONS(62), 1,
      sym_lateral_bar,
  [219] = 1,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
  [223] = 1,
    ACTIONS(66), 1,
      sym_comment_text,
  [227] = 1,
    ACTIONS(68), 1,
      aux_sym_structure_line_token1,
  [231] = 1,
    ACTIONS(50), 1,
      anon_sym_LF,
  [235] = 1,
    ACTIONS(70), 1,
      sym_comment_start,
  [239] = 1,
    ACTIONS(72), 1,
      sym_comment_text,
  [243] = 1,
    ACTIONS(74), 1,
      aux_sym_structure_line_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 17,
  [SMALL_STATE(4)] = 34,
  [SMALL_STATE(5)] = 51,
  [SMALL_STATE(6)] = 68,
  [SMALL_STATE(7)] = 79,
  [SMALL_STATE(8)] = 90,
  [SMALL_STATE(9)] = 103,
  [SMALL_STATE(10)] = 116,
  [SMALL_STATE(11)] = 124,
  [SMALL_STATE(12)] = 132,
  [SMALL_STATE(13)] = 140,
  [SMALL_STATE(14)] = 150,
  [SMALL_STATE(15)] = 160,
  [SMALL_STATE(16)] = 168,
  [SMALL_STATE(17)] = 173,
  [SMALL_STATE(18)] = 180,
  [SMALL_STATE(19)] = 187,
  [SMALL_STATE(20)] = 192,
  [SMALL_STATE(21)] = 197,
  [SMALL_STATE(22)] = 202,
  [SMALL_STATE(23)] = 207,
  [SMALL_STATE(24)] = 212,
  [SMALL_STATE(25)] = 219,
  [SMALL_STATE(26)] = 223,
  [SMALL_STATE(27)] = 227,
  [SMALL_STATE(28)] = 231,
  [SMALL_STATE(29)] = 235,
  [SMALL_STATE(30)] = 239,
  [SMALL_STATE(31)] = 243,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [9] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [12] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [14] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [16] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_line, 3, 0, 1),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_root_line, 3, 0, 1),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_structure_line, 5, 0, 3),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_structure_line, 5, 0, 3),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 4, 0, 2),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_comment, 3, 0, 4),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_structure_line, 6, 0, 3),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 5, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_line, 4, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_comment, 4, 0, 4),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [64] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_liotree(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "liotree",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
