/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 52
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SPACE = 1,
  aux_sym_root_token1 = 2,
  anon_sym_PIPE = 3,
  sym_format_space = 4,
  sym_depth_mark = 5,
  aux_sym_directory_name_token1 = 6,
  aux_sym_file_name_token1 = 7,
  aux_sym_file_name_token2 = 8,
  aux_sym_file_name_token3 = 9,
  anon_sym_GT = 10,
  aux_sym_comment_token1 = 11,
  anon_sym_PIPE_PIPE = 12,
  aux_sym_comment_newline_token1 = 13,
  aux_sym_comment_newline_token2 = 14,
  sym_source_file = 15,
  sym__item = 16,
  sym_root = 17,
  sym_root_bar = 18,
  sym_entry_bar = 19,
  sym_file_entry = 20,
  sym_directory_entry = 21,
  sym_directory_name = 22,
  sym_file_name = 23,
  sym_comment = 24,
  sym_comment_newline = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_file_entry_repeat1 = 27,
  aux_sym_directory_name_repeat1 = 28,
  aux_sym_comment_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SPACE] = " ",
  [aux_sym_root_token1] = "root_token1",
  [anon_sym_PIPE] = "|",
  [sym_format_space] = "format_space",
  [sym_depth_mark] = "depth_mark",
  [aux_sym_directory_name_token1] = "directory_name_token1",
  [aux_sym_file_name_token1] = "file_name_token1",
  [aux_sym_file_name_token2] = "file_name_token2",
  [aux_sym_file_name_token3] = "file_name_token3",
  [anon_sym_GT] = ">",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_PIPE_PIPE] = "||",
  [aux_sym_comment_newline_token1] = "comment_newline_token1",
  [aux_sym_comment_newline_token2] = "comment_newline_token2",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_root] = "root",
  [sym_root_bar] = "root_bar",
  [sym_entry_bar] = "entry_bar",
  [sym_file_entry] = "file_entry",
  [sym_directory_entry] = "directory_entry",
  [sym_directory_name] = "directory_name",
  [sym_file_name] = "file_name",
  [sym_comment] = "comment",
  [sym_comment_newline] = "comment_newline",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_file_entry_repeat1] = "file_entry_repeat1",
  [aux_sym_directory_name_repeat1] = "directory_name_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym_root_token1] = aux_sym_root_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_format_space] = sym_format_space,
  [sym_depth_mark] = sym_depth_mark,
  [aux_sym_directory_name_token1] = aux_sym_directory_name_token1,
  [aux_sym_file_name_token1] = aux_sym_file_name_token1,
  [aux_sym_file_name_token2] = aux_sym_file_name_token2,
  [aux_sym_file_name_token3] = aux_sym_file_name_token3,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [aux_sym_comment_newline_token1] = aux_sym_comment_newline_token1,
  [aux_sym_comment_newline_token2] = aux_sym_comment_newline_token2,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_root] = sym_root,
  [sym_root_bar] = sym_root_bar,
  [sym_entry_bar] = sym_entry_bar,
  [sym_file_entry] = sym_file_entry,
  [sym_directory_entry] = sym_directory_entry,
  [sym_directory_name] = sym_directory_name,
  [sym_file_name] = sym_file_name,
  [sym_comment] = sym_comment,
  [sym_comment_newline] = sym_comment_newline,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_file_entry_repeat1] = aux_sym_file_entry_repeat1,
  [aux_sym_directory_name_repeat1] = aux_sym_directory_name_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_root_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_format_space] = {
    .visible = true,
    .named = true,
  },
  [sym_depth_mark] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_directory_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_name_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_name_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_name_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_newline_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_newline_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_root] = {
    .visible = true,
    .named = true,
  },
  [sym_root_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_file_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_directory_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_directory_name] = {
    .visible = true,
    .named = true,
  },
  [sym_file_name] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_newline] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_directory_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bridge = 1,
  field_contents = 2,
  field_formatspace = 3,
  field_leaf = 4,
  field_name = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bridge] = "bridge",
  [field_contents] = "contents",
  [field_formatspace] = "formatspace",
  [field_leaf] = "leaf",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 3},
  [7] = {.index = 13, .length = 4},
  [8] = {.index = 17, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_formatspace, 1},
  [1] =
    {field_name, 2},
  [2] =
    {field_leaf, 1},
    {field_name, 3},
  [4] =
    {field_contents, 5},
    {field_leaf, 1},
    {field_name, 3},
  [7] =
    {field_bridge, 1},
    {field_leaf, 2},
    {field_name, 4},
  [10] =
    {field_contents, 6},
    {field_leaf, 1},
    {field_name, 3},
  [13] =
    {field_bridge, 1},
    {field_contents, 6},
    {field_leaf, 2},
    {field_name, 4},
  [17] =
    {field_bridge, 1},
    {field_contents, 7},
    {field_leaf, 2},
    {field_name, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\'') ADVANCE(19);
      if (lookahead == '>') ADVANCE(23);
      if (lookahead == '|') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\r') SKIP(0);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '>') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(14);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '|') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(25);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '|') ADVANCE(26);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '>') ADVANCE(23);
      if (lookahead == '|') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r') SKIP(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_root_token1);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(26);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_format_space);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_format_space);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(14);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_depth_mark);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_directory_name_token1);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(5);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_directory_name_token1);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(5);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_file_name_token1);
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_file_name_token1);
      if (lookahead == '\'') ADVANCE(19);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_file_name_token1);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_file_name_token2);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(3);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_file_name_token3);
      if (lookahead == '\'') ADVANCE(22);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(4);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '|') ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_comment_newline_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_comment_newline_token2);
      if (lookahead == '\t' ||
          lookahead == '\r') ADVANCE(28);
      if (('\n' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_comment_newline_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 28},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [aux_sym_root_token1] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_depth_mark] = ACTIONS(1),
    [aux_sym_directory_name_token1] = ACTIONS(1),
    [aux_sym_file_name_token1] = ACTIONS(1),
    [aux_sym_file_name_token2] = ACTIONS(1),
    [aux_sym_file_name_token3] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym__item] = STATE(3),
    [sym_root] = STATE(3),
    [sym_root_bar] = STATE(47),
    [sym_entry_bar] = STATE(42),
    [sym_file_entry] = STATE(3),
    [sym_directory_entry] = STATE(3),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PIPE] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    STATE(42), 1,
      sym_entry_bar,
    STATE(47), 1,
      sym_root_bar,
    ACTIONS(9), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
    STATE(4), 6,
      sym__item,
      sym_root,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_source_file_repeat1,
  [20] = 6,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(7), 1,
      anon_sym_GT,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(42), 1,
      sym_entry_bar,
    STATE(47), 1,
      sym_root_bar,
    STATE(4), 6,
      sym__item,
      sym_root,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_source_file_repeat1,
  [44] = 6,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(18), 1,
      anon_sym_GT,
    STATE(42), 1,
      sym_entry_bar,
    STATE(47), 1,
      sym_root_bar,
    STATE(4), 6,
      sym__item,
      sym_root,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_source_file_repeat1,
  [68] = 4,
    STATE(42), 1,
      sym_entry_bar,
    STATE(47), 1,
      sym_root_bar,
    ACTIONS(21), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
    STATE(8), 6,
      sym__item,
      sym_root,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_source_file_repeat1,
  [88] = 4,
    STATE(42), 1,
      sym_entry_bar,
    STATE(47), 1,
      sym_root_bar,
    ACTIONS(23), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
    STATE(9), 6,
      sym__item,
      sym_root,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_source_file_repeat1,
  [108] = 4,
    STATE(42), 1,
      sym_entry_bar,
    STATE(47), 1,
      sym_root_bar,
    ACTIONS(25), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
    STATE(2), 6,
      sym__item,
      sym_root,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_source_file_repeat1,
  [128] = 4,
    STATE(42), 1,
      sym_entry_bar,
    STATE(47), 1,
      sym_root_bar,
    ACTIONS(27), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
    STATE(4), 6,
      sym__item,
      sym_root,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_source_file_repeat1,
  [148] = 4,
    STATE(42), 1,
      sym_entry_bar,
    STATE(47), 1,
      sym_root_bar,
    ACTIONS(29), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
    STATE(4), 6,
      sym__item,
      sym_root,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_source_file_repeat1,
  [168] = 4,
    STATE(42), 1,
      sym_entry_bar,
    STATE(47), 1,
      sym_root_bar,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
    STATE(11), 6,
      sym__item,
      sym_root,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_source_file_repeat1,
  [188] = 4,
    STATE(42), 1,
      sym_entry_bar,
    STATE(47), 1,
      sym_root_bar,
    ACTIONS(33), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
    STATE(4), 6,
      sym__item,
      sym_root,
      sym_file_entry,
      sym_directory_entry,
      sym_comment,
      aux_sym_source_file_repeat1,
  [208] = 4,
    ACTIONS(35), 1,
      aux_sym_directory_name_token1,
    STATE(25), 1,
      sym_directory_name,
    STATE(28), 1,
      sym_file_name,
    ACTIONS(37), 3,
      aux_sym_file_name_token1,
      aux_sym_file_name_token2,
      aux_sym_file_name_token3,
  [223] = 4,
    ACTIONS(35), 1,
      aux_sym_directory_name_token1,
    STATE(30), 1,
      sym_file_name,
    STATE(34), 1,
      sym_directory_name,
    ACTIONS(37), 3,
      aux_sym_file_name_token1,
      aux_sym_file_name_token2,
      aux_sym_file_name_token3,
  [238] = 4,
    ACTIONS(39), 1,
      aux_sym_comment_token1,
    ACTIONS(41), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(43), 1,
      aux_sym_comment_newline_token1,
    STATE(16), 2,
      sym_comment_newline,
      aux_sym_comment_repeat1,
  [252] = 4,
    ACTIONS(43), 1,
      aux_sym_comment_newline_token1,
    ACTIONS(45), 1,
      aux_sym_comment_token1,
    ACTIONS(47), 1,
      anon_sym_PIPE_PIPE,
    STATE(14), 2,
      sym_comment_newline,
      aux_sym_comment_repeat1,
  [266] = 4,
    ACTIONS(49), 1,
      aux_sym_comment_token1,
    ACTIONS(52), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(54), 1,
      aux_sym_comment_newline_token1,
    STATE(16), 2,
      sym_comment_newline,
      aux_sym_comment_repeat1,
  [280] = 3,
    ACTIONS(59), 1,
      sym_format_space,
    STATE(20), 1,
      aux_sym_directory_name_repeat1,
    ACTIONS(57), 2,
      aux_sym_root_token1,
      anon_sym_GT,
  [291] = 1,
    ACTIONS(61), 4,
      ts_builtin_sym_end,
      aux_sym_root_token1,
      anon_sym_PIPE,
      anon_sym_GT,
  [298] = 3,
    ACTIONS(65), 1,
      sym_format_space,
    STATE(21), 1,
      aux_sym_directory_name_repeat1,
    ACTIONS(63), 2,
      aux_sym_root_token1,
      anon_sym_GT,
  [309] = 3,
    ACTIONS(69), 1,
      sym_format_space,
    STATE(20), 1,
      aux_sym_directory_name_repeat1,
    ACTIONS(67), 2,
      aux_sym_root_token1,
      anon_sym_GT,
  [320] = 3,
    ACTIONS(59), 1,
      sym_format_space,
    STATE(20), 1,
      aux_sym_directory_name_repeat1,
    ACTIONS(72), 2,
      aux_sym_root_token1,
      anon_sym_GT,
  [331] = 1,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      aux_sym_root_token1,
      anon_sym_PIPE,
      anon_sym_GT,
  [338] = 3,
    ACTIONS(78), 1,
      sym_format_space,
    STATE(17), 1,
      aux_sym_directory_name_repeat1,
    ACTIONS(76), 2,
      aux_sym_root_token1,
      anon_sym_GT,
  [349] = 3,
    ACTIONS(7), 1,
      anon_sym_GT,
    ACTIONS(80), 1,
      aux_sym_root_token1,
    STATE(51), 1,
      sym_comment,
  [359] = 3,
    ACTIONS(7), 1,
      anon_sym_GT,
    ACTIONS(82), 1,
      aux_sym_root_token1,
    STATE(46), 1,
      sym_comment,
  [369] = 2,
    ACTIONS(84), 1,
      aux_sym_comment_token1,
    ACTIONS(86), 2,
      anon_sym_PIPE_PIPE,
      aux_sym_comment_newline_token1,
  [377] = 1,
    ACTIONS(88), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
  [383] = 3,
    ACTIONS(7), 1,
      anon_sym_GT,
    ACTIONS(90), 1,
      aux_sym_root_token1,
    STATE(50), 1,
      sym_comment,
  [393] = 1,
    ACTIONS(92), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
  [399] = 3,
    ACTIONS(7), 1,
      anon_sym_GT,
    ACTIONS(94), 1,
      aux_sym_root_token1,
    STATE(43), 1,
      sym_comment,
  [409] = 1,
    ACTIONS(96), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
  [415] = 1,
    ACTIONS(98), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
  [421] = 1,
    ACTIONS(100), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
  [427] = 3,
    ACTIONS(7), 1,
      anon_sym_GT,
    ACTIONS(102), 1,
      aux_sym_root_token1,
    STATE(44), 1,
      sym_comment,
  [437] = 1,
    ACTIONS(104), 3,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      anon_sym_GT,
  [443] = 2,
    ACTIONS(106), 1,
      anon_sym_SPACE,
    ACTIONS(108), 1,
      sym_depth_mark,
  [450] = 2,
    ACTIONS(110), 1,
      anon_sym_SPACE,
    ACTIONS(112), 1,
      sym_depth_mark,
  [457] = 2,
    ACTIONS(114), 1,
      sym_depth_mark,
    STATE(38), 1,
      aux_sym_file_entry_repeat1,
  [464] = 2,
    ACTIONS(35), 1,
      aux_sym_directory_name_token1,
    STATE(24), 1,
      sym_directory_name,
  [471] = 2,
    ACTIONS(117), 1,
      sym_depth_mark,
    STATE(38), 1,
      aux_sym_file_entry_repeat1,
  [478] = 2,
    ACTIONS(108), 1,
      sym_depth_mark,
    ACTIONS(119), 1,
      anon_sym_SPACE,
  [485] = 2,
    ACTIONS(121), 1,
      sym_depth_mark,
    STATE(40), 1,
      aux_sym_file_entry_repeat1,
  [492] = 1,
    ACTIONS(123), 1,
      aux_sym_root_token1,
  [496] = 1,
    ACTIONS(125), 1,
      aux_sym_root_token1,
  [500] = 1,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
  [504] = 1,
    ACTIONS(129), 1,
      aux_sym_root_token1,
  [508] = 1,
    ACTIONS(131), 1,
      anon_sym_SPACE,
  [512] = 1,
    ACTIONS(133), 1,
      aux_sym_comment_newline_token2,
  [516] = 1,
    ACTIONS(135), 1,
      anon_sym_PIPE,
  [520] = 1,
    ACTIONS(137), 1,
      aux_sym_root_token1,
  [524] = 1,
    ACTIONS(139), 1,
      aux_sym_root_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 68,
  [SMALL_STATE(6)] = 88,
  [SMALL_STATE(7)] = 108,
  [SMALL_STATE(8)] = 128,
  [SMALL_STATE(9)] = 148,
  [SMALL_STATE(10)] = 168,
  [SMALL_STATE(11)] = 188,
  [SMALL_STATE(12)] = 208,
  [SMALL_STATE(13)] = 223,
  [SMALL_STATE(14)] = 238,
  [SMALL_STATE(15)] = 252,
  [SMALL_STATE(16)] = 266,
  [SMALL_STATE(17)] = 280,
  [SMALL_STATE(18)] = 291,
  [SMALL_STATE(19)] = 298,
  [SMALL_STATE(20)] = 309,
  [SMALL_STATE(21)] = 320,
  [SMALL_STATE(22)] = 331,
  [SMALL_STATE(23)] = 338,
  [SMALL_STATE(24)] = 349,
  [SMALL_STATE(25)] = 359,
  [SMALL_STATE(26)] = 369,
  [SMALL_STATE(27)] = 377,
  [SMALL_STATE(28)] = 383,
  [SMALL_STATE(29)] = 393,
  [SMALL_STATE(30)] = 399,
  [SMALL_STATE(31)] = 409,
  [SMALL_STATE(32)] = 415,
  [SMALL_STATE(33)] = 421,
  [SMALL_STATE(34)] = 427,
  [SMALL_STATE(35)] = 437,
  [SMALL_STATE(36)] = 443,
  [SMALL_STATE(37)] = 450,
  [SMALL_STATE(38)] = 457,
  [SMALL_STATE(39)] = 464,
  [SMALL_STATE(40)] = 471,
  [SMALL_STATE(41)] = 478,
  [SMALL_STATE(42)] = 485,
  [SMALL_STATE(43)] = 492,
  [SMALL_STATE(44)] = 496,
  [SMALL_STATE(45)] = 500,
  [SMALL_STATE(46)] = 504,
  [SMALL_STATE(47)] = 508,
  [SMALL_STATE(48)] = 512,
  [SMALL_STATE(49)] = 516,
  [SMALL_STATE(50)] = 520,
  [SMALL_STATE(51)] = 524,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 6, 0, 4),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 6, 0, 3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 6, 0, 5),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 5, 0, 3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 7, 0, 6),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 7, 0, 7),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 7, 0, 5),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directory_entry, 8, 0, 8),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_name, 2, 0, 1),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_name, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_directory_name_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_directory_name_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_name, 2, 0, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directory_name, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_newline, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_newline, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 4, 0, 2),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 5, 0, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_entry, 6, 0, 3),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_entry, 7, 0, 5),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_entry, 5, 0, 3),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_entry, 6, 0, 5),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_entry_repeat1, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_bar, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry_bar, 1, 0, 0),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [127] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_liotree(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "liotree",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
