/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 35
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SPACE = 1,
  aux_sym_root_token1 = 2,
  anon_sym_PIPE = 3,
  sym_depth_mark = 4,
  sym_directory_name = 5,
  sym_file_name = 6,
  anon_sym_GT = 7,
  aux_sym_comment_token1 = 8,
  anon_sym_PIPE_PIPE = 9,
  aux_sym_comment_newline_token1 = 10,
  aux_sym_comment_newline_token2 = 11,
  sym_source_file = 12,
  sym__node = 13,
  sym_root = 14,
  sym_root_bar = 15,
  sym_entry_bar = 16,
  sym_entry = 17,
  sym_comment = 18,
  sym_comment_newline = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_entry_repeat1 = 21,
  aux_sym_comment_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SPACE] = " ",
  [aux_sym_root_token1] = "root_token1",
  [anon_sym_PIPE] = "|",
  [sym_depth_mark] = "depth_mark",
  [sym_directory_name] = "directory_name",
  [sym_file_name] = "file_name",
  [anon_sym_GT] = ">",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_PIPE_PIPE] = "||",
  [aux_sym_comment_newline_token1] = "comment_newline_token1",
  [aux_sym_comment_newline_token2] = "comment_newline_token2",
  [sym_source_file] = "source_file",
  [sym__node] = "_node",
  [sym_root] = "root",
  [sym_root_bar] = "root_bar",
  [sym_entry_bar] = "entry_bar",
  [sym_entry] = "entry",
  [sym_comment] = "comment",
  [sym_comment_newline] = "comment_newline",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_entry_repeat1] = "entry_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [aux_sym_root_token1] = aux_sym_root_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_depth_mark] = sym_depth_mark,
  [sym_directory_name] = sym_directory_name,
  [sym_file_name] = sym_file_name,
  [anon_sym_GT] = anon_sym_GT,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [aux_sym_comment_newline_token1] = aux_sym_comment_newline_token1,
  [aux_sym_comment_newline_token2] = aux_sym_comment_newline_token2,
  [sym_source_file] = sym_source_file,
  [sym__node] = sym__node,
  [sym_root] = sym_root,
  [sym_root_bar] = sym_root_bar,
  [sym_entry_bar] = sym_entry_bar,
  [sym_entry] = sym_entry,
  [sym_comment] = sym_comment,
  [sym_comment_newline] = sym_comment_newline,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_entry_repeat1] = aux_sym_entry_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_root_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_depth_mark] = {
    .visible = true,
    .named = true,
  },
  [sym_directory_name] = {
    .visible = true,
    .named = true,
  },
  [sym_file_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_newline_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_newline_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_root] = {
    .visible = true,
    .named = true,
  },
  [sym_root_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_bar] = {
    .visible = true,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_newline] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entry_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_bridge = 1,
  field_leaf = 2,
  field_name = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bridge] = "bridge",
  [field_leaf] = "leaf",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 2},
  [1] =
    {field_leaf, 1},
    {field_name, 3},
  [3] =
    {field_bridge, 1},
    {field_leaf, 2},
    {field_name, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '>') ADVANCE(14);
      if (lookahead == '|') ADVANCE(10);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '|') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\r') SKIP(2);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '|') ADVANCE(17);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '|') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_root_token1);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(17);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_depth_mark);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_directory_name);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(3);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_file_name);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != '|') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '|') ADVANCE(15);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_comment_newline_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comment_newline_token2);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(19);
      if (('\n' <= lookahead && lookahead <= '\f')) ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_comment_newline_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 19},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_root_token1] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_depth_mark] = ACTIONS(1),
    [sym_directory_name] = ACTIONS(1),
    [sym_file_name] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(25),
    [sym__node] = STATE(2),
    [sym_root] = STATE(2),
    [sym_root_bar] = STATE(27),
    [sym_entry_bar] = STATE(11),
    [sym_entry] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PIPE] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      anon_sym_PIPE,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_entry_bar,
    STATE(27), 1,
      sym_root_bar,
    STATE(3), 4,
      sym__node,
      sym_root,
      sym_entry,
      aux_sym_source_file_repeat1,
  [19] = 5,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      anon_sym_PIPE,
    STATE(11), 1,
      sym_entry_bar,
    STATE(27), 1,
      sym_root_bar,
    STATE(3), 4,
      sym__node,
      sym_root,
      sym_entry,
      aux_sym_source_file_repeat1,
  [38] = 4,
    ACTIONS(14), 1,
      aux_sym_comment_token1,
    ACTIONS(16), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(18), 1,
      aux_sym_comment_newline_token1,
    STATE(5), 2,
      sym_comment_newline,
      aux_sym_comment_repeat1,
  [52] = 4,
    ACTIONS(18), 1,
      aux_sym_comment_newline_token1,
    ACTIONS(20), 1,
      aux_sym_comment_token1,
    ACTIONS(22), 1,
      anon_sym_PIPE_PIPE,
    STATE(6), 2,
      sym_comment_newline,
      aux_sym_comment_repeat1,
  [66] = 4,
    ACTIONS(24), 1,
      aux_sym_comment_token1,
    ACTIONS(27), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(29), 1,
      aux_sym_comment_newline_token1,
    STATE(6), 2,
      sym_comment_newline,
      aux_sym_comment_repeat1,
  [80] = 3,
    ACTIONS(32), 1,
      aux_sym_root_token1,
    ACTIONS(34), 1,
      anon_sym_GT,
    STATE(28), 1,
      sym_comment,
  [90] = 3,
    ACTIONS(34), 1,
      anon_sym_GT,
    ACTIONS(36), 1,
      aux_sym_root_token1,
    STATE(33), 1,
      sym_comment,
  [100] = 3,
    ACTIONS(34), 1,
      anon_sym_GT,
    ACTIONS(38), 1,
      aux_sym_root_token1,
    STATE(34), 1,
      sym_comment,
  [110] = 2,
    ACTIONS(40), 1,
      aux_sym_comment_token1,
    ACTIONS(42), 2,
      anon_sym_PIPE_PIPE,
      aux_sym_comment_newline_token1,
  [118] = 2,
    ACTIONS(44), 1,
      sym_depth_mark,
    STATE(14), 1,
      aux_sym_entry_repeat1,
  [125] = 2,
    ACTIONS(46), 1,
      sym_depth_mark,
    STATE(12), 1,
      aux_sym_entry_repeat1,
  [132] = 2,
    ACTIONS(49), 1,
      anon_sym_SPACE,
    ACTIONS(51), 1,
      sym_depth_mark,
  [139] = 2,
    ACTIONS(53), 1,
      sym_depth_mark,
    STATE(12), 1,
      aux_sym_entry_repeat1,
  [146] = 1,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
  [151] = 2,
    ACTIONS(57), 1,
      anon_sym_SPACE,
    ACTIONS(59), 1,
      sym_depth_mark,
  [158] = 2,
    ACTIONS(61), 1,
      sym_directory_name,
    ACTIONS(63), 1,
      sym_file_name,
  [165] = 2,
    ACTIONS(51), 1,
      sym_depth_mark,
    ACTIONS(65), 1,
      anon_sym_SPACE,
  [172] = 2,
    ACTIONS(67), 1,
      sym_directory_name,
    ACTIONS(69), 1,
      sym_file_name,
  [179] = 1,
    ACTIONS(71), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
  [184] = 1,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
  [189] = 1,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
  [194] = 1,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
  [199] = 1,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
  [204] = 1,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
  [208] = 1,
    ACTIONS(83), 1,
      sym_directory_name,
  [212] = 1,
    ACTIONS(85), 1,
      anon_sym_SPACE,
  [216] = 1,
    ACTIONS(87), 1,
      aux_sym_root_token1,
  [220] = 1,
    ACTIONS(89), 1,
      aux_sym_root_token1,
  [224] = 1,
    ACTIONS(91), 1,
      aux_sym_root_token1,
  [228] = 1,
    ACTIONS(93), 1,
      aux_sym_comment_newline_token2,
  [232] = 1,
    ACTIONS(95), 1,
      anon_sym_PIPE,
  [236] = 1,
    ACTIONS(97), 1,
      aux_sym_root_token1,
  [240] = 1,
    ACTIONS(99), 1,
      aux_sym_root_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 19,
  [SMALL_STATE(4)] = 38,
  [SMALL_STATE(5)] = 52,
  [SMALL_STATE(6)] = 66,
  [SMALL_STATE(7)] = 80,
  [SMALL_STATE(8)] = 90,
  [SMALL_STATE(9)] = 100,
  [SMALL_STATE(10)] = 110,
  [SMALL_STATE(11)] = 118,
  [SMALL_STATE(12)] = 125,
  [SMALL_STATE(13)] = 132,
  [SMALL_STATE(14)] = 139,
  [SMALL_STATE(15)] = 146,
  [SMALL_STATE(16)] = 151,
  [SMALL_STATE(17)] = 158,
  [SMALL_STATE(18)] = 165,
  [SMALL_STATE(19)] = 172,
  [SMALL_STATE(20)] = 179,
  [SMALL_STATE(21)] = 184,
  [SMALL_STATE(22)] = 189,
  [SMALL_STATE(23)] = 194,
  [SMALL_STATE(24)] = 199,
  [SMALL_STATE(25)] = 204,
  [SMALL_STATE(26)] = 208,
  [SMALL_STATE(27)] = 212,
  [SMALL_STATE(28)] = 216,
  [SMALL_STATE(29)] = 220,
  [SMALL_STATE(30)] = 224,
  [SMALL_STATE(31)] = 228,
  [SMALL_STATE(32)] = 232,
  [SMALL_STATE(33)] = 236,
  [SMALL_STATE(34)] = 240,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [14] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [16] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [18] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_newline, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_newline, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_entry_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_entry_repeat1, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 4, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root_bar, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entry_bar, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 5, 0, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_root, 5, 0, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 6, 0, 3),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 6, 0, 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 7, 0, 3),
  [81] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_liotree(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "liotree",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
